<?php
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.



// Example 1:

$s = "abcd";
$t = "abcde";
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// $s = "";
// $t = "y";
// Output: "y"


// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.
class Solution
{

  /**
   * @param String $s
   * @param String $t
   * @return String
   */
  function findTheDifference($s, $t)
  {
    if ($s === '') {
      return $t;
    }

    $string_parts = array_map('str_split', ['s' => $s, "t" => $t]);


    $s_char_counts = array_count_values($string_parts['s']);
    $t_char_counts = array_count_values($string_parts['t']);


    foreach ($t_char_counts as $char => $count) {
      if (!isset($s_char_counts[$char])) {
        return $char;
      }

      if ($s_char_counts[$char] !== $count) {
        return $char;
      }
    }
  }
}

$s = "ae";
$t = "aea";
echo (new Solution())->findTheDifference($s, $t);
